### ISSUE TITLE
UTF8 Shapefiles

### ISSUE THREAD

**Issue by rcoup** [mweisman/gdbflee#1]
@nvkelso says it would be awesome to have UTF8 shapefiles to come out. The magic trick is to pass `ENCODING=UTF-8` to `OGRDatasource.CreateLayer()` - OGR will then set the header of the DBF file to 0/Unknown and create a .cpg file. Then ArcMap will detect and use the shapefiles as UTF8. So will OGR (ie. QGis/etc)

http://www.gdal.org/ogr/classOGRDataSource.html#a39cfc6e0ee790506d7638b0dce03c7da
http://www.gdal.org/ogr/drv_shapefile.html (not that it's obvious).

**Comment by mweisman** [comment]
This should be fixed with 70bede7. I don't have a copy of ArcGIS to test that this is working right, but there are now .cpg files with shapefiles.

**Comment by nvkelso** [comment]
Server error for me. I'll email MWeisman my testing file.

_n
